server
{
	listen 5000;
	root /var/lib/www/;
	location / {
		index index.html;
	}
	location /delete/ {
		alias /var/lib/www/;
                fastcgi_pass unix:/run/fcgiwrap.socket;
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME /var/lib/www/cgi/delete_cgi.sh;
                fastcgi_param PATH_INFO $uri;
		fastcgi_param PATH_TRANSLATED $request_filename;
                limit_except DELETE { }
	}
	location /post/ {
		alias /var/lib/www/;
		fastcgi_pass unix:/run/fcgiwrap.socket;
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME /var/lib/www/cgi/post_cgi.sh;
                fastcgi_param PATH_INFO $uri;
		fastcgi_param PATH_TRANSLATED $request_filename;
		limit_except POST { }
		client_max_body_size 1024;
	}
	location /cgi_py/ {
		alias /var/lib/www/cgi/;
                fastcgi_pass unix:/run/fcgiwrap.socket;
                include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $request_filename;
		fastcgi_param PATH_INFO $uri;
		fastcgi_param PATH_TRANSLATED $request_filename;
	}
}
