http {
    server {
        listen 0.0.0.0:8080;
        server_name localhost;
        
        location /upload {
            upload_store ./uploads;
            limit POST;
            root ./;
        }
    }
}
