http {
    server {
        listen 0.0.0.0:8080;
        server_name localhost;
        root /var/www/html;
        client_max_body_size 10M;
        
        location /upload {
            limit POST;
            upload_store ./uploads;
            root ./;
        }
        
        location / {
            root ./www;
            autoindex on;
        }
    }
}
