http
{
    root /tmp/webserv_test;
    client_max_body_size 10M;
    error_page 404 /404.html;
    autoindex on;
    index /index.html;
    
    server {
        listen 0.0.0.0:8080;
        server_name localhost;
        root /tmp/webserv_test;
        
        location / {
            root /tmp/webserv_test;
            limit GET POST;
        }
        
        location /upload {
            root /tmp/webserv_test;
            limit GET POST;
            upload_store /tmp/webserv_test/uploads;
        }
    }
}
